server:
  port: 9201
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
service:
  vault: ${VAULT_ENABLE:true}
  limit: false
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:debug}
    org:
      springframework:
        security: ${SECURITY_LOG_LEVEL:debug}
    com:
      elpsykongroo: ${APP_LOG_LEVEL:debug}
